import random from '../utils/random'

export const cities = [
  'Bulawayo, ZW',
  'Harare, ZW',
  'Kitwe, ZM',
  'Lusaka, ZM',
  'Cape Town, ZA',
  'Benoni, ZA',
  'Bloemfontein, ZA',
  'Boksburg, ZA',
  'Durban, ZA',
  'East London, ZA',
  'Johannesburg, ZA',
  'Newcastle, ZA',
  'Pietermaritzburg, ZA',
  'Port Elizabeth, ZA',
  'Pretoria, ZA',
  'Soweto, ZA',
  'Tembisa, ZA',
  'Vereeniging, ZA',
  'Welkom, ZA',
  'Aden, YE',
  'Al Ḩudaydah, YE',
  'Sanaa, YE',
  'Ta‘izz, YE',
  'Pristina, XK',
  'Biên Hòa, VN',
  'Da Nang, VN',
  'Haiphong, VN',
  'Hanoi, VN',
  'Ho Chi Minh City, VN',
  'Maturín, VE',
  'Barcelona, VE',
  'Barquisimeto, VE',
  'Caracas, VE',
  'Ciudad Guayana, VE',
  'Maracaibo, VE',
  'Maracay, VE',
  'Valencia, VE',
  'Namangan, UZ',
  'Tashkent, UZ',
  'Montevideo, UY',
  'Metropolitan Government of Nashville-Davidson (balance), TN',
  'Seattle, WA',
  'Portland, OR',
  'El Paso, TX',
  'Las Vegas, NV',
  'Albuquerque, NM',
  'Denver, CO',
  'Colorado Springs, CO',
  'San Jose, CA',
  'San Francisco, CA',
  'San Diego, CA',
  'Sacramento, CA',
  'Los Angeles, CA',
  'Long Beach, CA',
  'Fresno, CA',
  'Tucson, AZ',
  'Phoenix, AZ',
  'Mesa, AZ',
  'Milwaukee, WI',
  'Staten Island, NY',
  'Borough of Queens, NY',
  'New York City, NY',
  'Manhattan, NY',
  'Brooklyn, NY',
  'Borough of Bronx, NY',
  'Omaha, NE',
  'Detroit, MI',
  'South Boston, MA',
  'Boston, MA',
  'Chicago, IL',
  'Virginia Beach, VA',
  'San Antonio, TX',
  'Houston, TX',
  'Fort Worth, TX',
  'Dallas, TX',
  'Austin, TX',
  'New South Memphis, TN',
  'Nashville, TN',
  'Memphis, TN',
  'Philadelphia, PA',
  'Oklahoma City, OK',
  'Columbus, OH',
  'Raleigh, NC',
  'Charlotte, NC',
  'Kansas City, MO',
  'Baltimore, MD',
  'Indianapolis, IN',
  'Atlanta, GA',
  'Jacksonville, FL',
  'Washington, D. C., DC',
  'Kampala, UG',
  'Dnipropetrovsk, UA',
  'Donets’k, UA',
  'Kharkiv, UA',
  'Kryvyy Rih, UA',
  'Kiev, UA',
  'Luhans’k, UA',
  "L'viv, UA",
  'Mariupol, UA',
  'Mykolayiv, UA',
  'Odessa, UA',
  'Zaporizhzhya, UA',
  'Dar es Salaam, TZ',
  'Mwanza, TZ',
  'Zanzibar, TZ',
  'Taoyuan City, TW',
  'Hsinchu, TW',
  'Kaohsiung, TW',
  'Banqiao, TW',
  'Taichung, TW',
  'Tainan, TW',
  'Taipei, TW',
  'Karabağlar, TR',
  'Sultangazi, TR',
  'Bahçelievler, TR',
  'Çankaya, TR',
  'Bağcılar, TR',
  'Bursa, TR',
  'Esenler, TR',
  'İstanbul, TR',
  'Maltepe, TR',
  'Umraniye, TR',
  'Üsküdar, TR',
  'Adana, TR',
  'Ankara, TR',
  'Antalya, TR',
  'Diyarbakır, TR',
  'Erzurum, TR',
  'Eskişehir, TR',
  'Gaziantep, TR',
  'İzmir, TR',
  'Kayseri, TR',
  'Konya, TR',
  'Malatya, TR',
  'Mercin, TR',
  'Şanlıurfa, TR',
  'Tunis, TN',
  'Ashgabat, TM',
  'Dushanbe, TJ',
  'Bangkok, TH',
  'Lomé, TG',
  "N'Djamena, TD",
  'Damascus, SY',
  'Aleppo, SY',
  'Ḩamāh, SY',
  'Homs, SY',
  'San Salvador, SV',
  'Hargeysa, SO',
  'Mogadishu, SO',
  'Dakar, SN',
  'Grand Dakar, SN',
  'Pikine, SN',
  'Touba, SN',
  'Freetown, SL',
  'Bratislava, SK',
  'Singapore, SG',
  'Göteborg, SE',
  'Stockholm, SE',
  'Khartoum, SD',
  'Port Sudan, SD',
  'Kassala, SD',
  'Omdurman, SD',
  'Dammam, SA',
  'Medina, SA',
  'Riyadh, SA',
  'Ta’if, SA',
  'Jeddah, SA',
  'Mecca, SA',
  'Sulţānah, SA',
  'Tabūk, SA',
  'Kigali, RW',
  'Kalininskiy, RU',
  'Khabarovsk Vtoroy, RU',
  'Irkutsk, RU',
  'Khabarovsk, RU',
  'Vladivostok, RU',
  'Barnaul, RU',
  'Chelyabinsk, RU',
  'Kemerovo, RU',
  'Krasnoyarsk, RU',
  'Novokuznetsk, RU',
  'Novosibirsk, RU',
  'Omsk, RU',
  'Tomsk, RU',
  'Tyumen, RU',
  'Yekaterinburg, RU',
  'Astrakhan’, RU',
  'Bryansk, RU',
  'Cheboksary, RU',
  'Ivanovo, RU',
  'Izhevsk, RU',
  'Kaliningrad, RU',
  'Kazan, RU',
  'Kirov, RU',
  'Krasnodar, RU',
  'Kursk, RU',
  'Lipetsk, RU',
  'Magnitogorsk, RU',
  'Makhachkala, RU',
  'Moscow, RU',
  'Naberezhnyye Chelny, RU',
  'Nizhniy Novgorod, RU',
  'Orenburg, RU',
  'Penza, RU',
  'Perm’, RU',
  'Rostov-na-Donu, RU',
  'Ryazan’, RU',
  'Samara, RU',
  'Saint Petersburg, RU',
  'Saratov, RU',
  'Tol’yatti, RU',
  'Tula, RU',
  'Tver, RU',
  'Ufa, RU',
  'Ulyanovsk, RU',
  'Volgograd, RU',
  'Voronezh, RU',
  'Yaroslavl, RU',
  'Belgrade, RS',
  'Bucharest, RO',
  'Asunción, PY',
  'Lisbon, PT',
  'East Jerusalem, PS',
  'Gaza, PS',
  'San Juan, PR',
  'Gdańsk, PL',
  'Kraków, PL',
  'Łódź, PL',
  'Poznań, PL',
  'Szczecin, PL',
  'Wrocław, PL',
  'Warsaw, PL',
  'Bahāwalpur, PK',
  'Faisalābād, PK',
  'Gujrānwāla, PK',
  'Hyderābād, PK',
  'Islamabad, PK',
  'Karachi, PK',
  'Kotli, PK',
  'Lahore, PK',
  'Multān, PK',
  'Muzaffarābād, PK',
  'Peshāwar, PK',
  'Quetta, PK',
  'Rāwalpindi, PK',
  'Sargodha, PK',
  'Siālkot, PK',
  'Sukkur, PK',
  'Pasig City, PH',
  'Malingao, PH',
  'Antipolo, PH',
  'Bacolod City, PH',
  'Budta, PH',
  'Cagayan de Oro, PH',
  'Cebu City, PH',
  'Dasmariñas, PH',
  'Davao, PH',
  'General Santos, PH',
  'Makati City, PH',
  'Manila, PH',
  'Mansilingan, PH',
  'Quezon City, PH',
  'Taguig, PH',
  'Zamboanga, PH',
  'Arequipa, PE',
  'Callao, PE',
  'Lima, PE',
  'Chiclayo, PE',
  'Iquitos, PE',
  'Trujillo, PE',
  'Panamá, PA',
  'Muscat, OM',
  'Auckland, NZ',
  'Kathmandu, NP',
  'Oslo, NO',
  'Amsterdam, NL',
  'Rotterdam, NL',
  'The Hague, NL',
  'Managua, NI',
  'Aba, NG',
  'Abeokuta, NG',
  'Abuja, NG',
  'Ado-Ekiti, NG',
  'Akure, NG',
  'Benin City, NG',
  'Calabar, NG',
  'Ebute Ikorodu, NG',
  'Enugu, NG',
  'Ibadan, NG',
  'Ilorin, NG',
  'Jos, NG',
  'Kaduna, NG',
  'Kano, NG',
  'Katsina, NG',
  'Lagos, NG',
  'Maiduguri, NG',
  'Onitsha, NG',
  'Oyo, NG',
  'Port Harcourt, NG',
  'Sokoto, NG',
  'Uyo, NG',
  'Warri, NG',
  'Zaria, NG',
  'Niamey, NE',
  'Beira, MZ',
  'Maputo, MZ',
  'Matola, MZ',
  'Subang Jaya, MY',
  'Kampung Baru Subang, MY',
  'Kota Bharu, MY',
  'Kuching, MY',
  'Kuala Lumpur, MY',
  'Petaling Jaya, MY',
  'Ipoh, MY',
  'Kota Kinabalu, MY',
  'Klang, MY',
  'Shah Alam, MY',
  'Johor Bahru, MY',
  'Aguascalientes, MX',
  'Chihuahua, MX',
  'Ciudad Juárez, MX',
  'Culiacán, MX',
  'Victoria de Durango, MX',
  'Guadalajara, MX',
  'Guadalupe, MX',
  'Hermosillo, MX',
  'León, MX',
  'Mexicali, MX',
  'Monterrey, MX',
  'Morelia, MX',
  'Santiago de Querétaro, MX',
  'Saltillo, MX',
  'San Luis Potosí, MX',
  'San Nicolás de los Garza, MX',
  'Tijuana, MX',
  'Tlaquepaque, MX',
  'Tonalá, MX',
  'Torreón, MX',
  'Zapopan, MX',
  'Cuauhtémoc, MX',
  'Venustiano Carranza, MX',
  'Acapulco, MX',
  'Ciudad López Mateos, MX',
  'Azcapotzalco, MX',
  'Cancún, MX',
  'Mexico City, MX',
  'Ciudad Nezahualcóyotl, MX',
  'Coyoacán, MX',
  'Ecatepec, MX',
  'Iztapalapa, MX',
  'Xalapa de Enríquez, MX',
  'Heroica Matamoros, MX',
  'Mérida, MX',
  'Naucalpan de Juárez, MX',
  'Puebla de Zaragoza, MX',
  'Reynosa, MX',
  'Santa María Chimalhuacán, MX',
  'Cuautitlán Izcalli, MX',
  'Tlalnepantla, MX',
  'Tlalpan, MX',
  'Toluca de Lerdo, MX',
  'Tuxtla Gutiérrez, MX',
  'Veracruz, MX',
  'Gustavo A. Madero, MX',
  'Alvaro Obregón, MX',
  'Xochimilco, MX',
  'Gustavo A. Madero, MX',
  'Blantyre, MW',
  'Lilongwe, MW',
  'Nouakchott, MR',
  'Macau, MO',
  'Ulaanbaatar, MN',
  'Nay Pyi Taw, MM',
  'Mandalay, MM',
  'Mawlamyine, MM',
  'Rangoon, MM',
  'Bamako, ML',
  'Skopje, MK',
  'Antananarivo, MG',
  'Chişinău, MD',
  'Agadir, MA',
  'Casablanca, MA',
  'Fès, MA',
  'Marrakesh, MA',
  'Meknès, MA',
  'Oujda, MA',
  'Rabat, MA',
  'Sale, MA',
  'Tangier, MA',
  'Tripoli, LY',
  'Benghazi, LY',
  'Riga, LV',
  'Vilnius, LT',
  'Monrovia, LR',
  'Colombo, LK',
  'Beirut, LB',
  'Ra’s Bayrūt, LB',
  'Almaty, KZ',
  'Shymkent, KZ',
  'Karagandy, KZ',
  'Al Aḩmadī, KW',
  'Seongnam, KR',
  'Ansan, KR',
  'Anyang, KR',
  'Changwon, KR',
  'Jeju, KR',
  'Cheongju, KR',
  'Jeonju, KR',
  'Hwaseong, KR',
  'Incheon, KR',
  'Goyang, KR',
  'Gwangju, KR',
  'Pohang, KR',
  'Bucheon, KR',
  'Busan, KR',
  'Seoul, KR',
  'Suigen, KR',
  'Daegu, KR',
  'Daejeon, KR',
  'Vijongbu, KR',
  'Ulsan, KR',
  'Hamhŭng, KP',
  'Namp’o, KP',
  'Pyongyang, KP',
  'Takeo, KH',
  'Phnom Penh, KH',
  'Bishkek, KG',
  'Mombasa, KE',
  'Nairobi, KE',
  'Sendai, JP',
  'Suginami-ku, JP',
  'Ōta-ku, JP',
  'Katsushika-ku, JP',
  'Itabashi-ku, JP',
  'Adachi-ku, JP',
  'Saitama, JP',
  'Kōtō-ku, JP',
  'Edogawa-ku, JP',
  'Sapporo, JP',
  'Chiba, JP',
  'Sendai-shi, JP',
  'Matsuyama-shi, JP',
  'Amagasaki, JP',
  'Fukuoka-shi, JP',
  'Funabashi, JP',
  'Hachiōji, JP',
  'Hamamatsu, JP',
  'Himeji, JP',
  'Hirakata, JP',
  'Hiroshima-shi, JP',
  'Ichikawa, JP',
  'Kagoshima-shi, JP',
  'Kanazawa-shi, JP',
  'Kawaguchi, JP',
  'Kawasaki, JP',
  'Kitakyūshū, JP',
  'Kōbe-shi, JP',
  'Kumamoto-shi, JP',
  'Kurashiki, JP',
  'Kyoto, JP',
  'Matsudo, JP',
  'Nagasaki-shi, JP',
  'Nagoya-shi, JP',
  'Nerima-ku, JP',
  'Niigata-shi, JP',
  'Nishinomiya, JP',
  'Ōita-shi, JP',
  'Okayama-shi, JP',
  'Ōsaka-shi, JP',
  'Sagamihara, JP',
  'Sakai, JP',
  'Shizuoka-shi, JP',
  'Tokyo, JP',
  'Utsunomiya-shi, JP',
  'Yokohama-shi, JP',
  'Yokosuka, JP',
  'Yono, JP',
  'Amman, JO',
  'Zarqa, JO',
  'Kingston, JM',
  'New Kingston, JM',
  'Genova, IT',
  'Milano, IT',
  'Napoli, IT',
  'Rome, IT',
  'Turin, IT',
  'Palermo, IT',
  'Zahedan, IR',
  'Eşfahān, IR',
  'Ahvaz, IR',
  'Arāk, IR',
  'Ardabīl, IR',
  'Hamadān, IR',
  'Karaj, IR',
  'Kermān, IR',
  'Kermānshāh, IR',
  'Mashhad, IR',
  'Orūmīyeh, IR',
  'Qom, IR',
  'Rasht, IR',
  'Shīrāz, IR',
  'Tabrīz, IR',
  'Tehrān, IR',
  'Yazd, IR',
  'Kahrīz, IR',
  'Āzādshahr, IR',
  'Al Başrat al Qadīmah, IQ',
  'Abū Ghurayb, IQ',
  'Al Başrah, IQ',
  'Mosul, IQ',
  'Al Mawşil al Jadīdah, IQ',
  'An Najaf al Ashraf, IQ',
  'An Nāşirīyah, IQ',
  'As Sulaymānīyah, IQ',
  'Baghdad, IQ',
  'Erbil, IQ',
  'Karbala, IQ',
  'Kirkuk, IQ',
  'Shivaji Nagar, IN',
  'Navi Mumbai, IN',
  'Nangi, IN',
  'Āgra, IN',
  'Ahmedabad, IN',
  'Ajmer, IN',
  'Akola, IN',
  'Alīgarh, IN',
  'Allahābād, IN',
  'Amrāvati, IN',
  'Amritsar, IN',
  'Āsansol, IN',
  'Aurangābād, IN',
  'Bangalore, IN',
  'Bareilly, IN',
  'Belgaum, IN',
  'Bhātpāra, IN',
  'Bhāvnagar, IN',
  'Bhayandar, IN',
  'Bhilai, IN',
  'Bhiwandi, IN',
  'Bhopal, IN',
  'Bhubaneshwar, IN',
  'Bīkāner, IN',
  'Bilimora, IN',
  'Bokāro, IN',
  'Mumbai, IN',
  'Borivli, IN',
  'Kolkata, IN',
  'Chandigarh, IN',
  'Cochin, IN',
  'Coimbatore, IN',
  'Cuttack, IN',
  'Dehradun, IN',
  'Delhi, IN',
  'Dombivli, IN',
  'Durgāpur, IN',
  'Farīdābād, IN',
  'Guwāhāti, IN',
  'Gaya, IN',
  'Ghāziābād, IN',
  'Gorakhpur, IN',
  'Gorakhpur, IN',
  'Gulbarga, IN',
  'Guntūr, IN',
  'Gwalior, IN',
  'Hāora, IN',
  'Hubli, IN',
  'Hyderabad, IN',
  'Indore, IN',
  'Jabalpur, IN',
  'Jaipur, IN',
  'Jālgaon, IN',
  'Jammu, IN',
  'Jāmnagar, IN',
  'Jamshedpur, IN',
  'Jhānsi, IN',
  'Jodhpur, IN',
  'Jalandhar, IN',
  'Kalyān, IN',
  'Kānpur, IN',
  'Karol Bāgh, IN',
  'Kolhāpur, IN',
  'Korba, IN',
  'Kota, IN',
  'Kozhikode, IN',
  'Lucknow, IN',
  'Ludhiāna, IN',
  'Chennai, IN',
  'Madurai, IN',
  'Mālegaon, IN',
  'Mangalore, IN',
  'Meerut, IN',
  'Morādābād, IN',
  'Mysore, IN',
  'Nāgpur, IN',
  'Nanded, IN',
  'Nāsik, IN',
  'Nellore, IN',
  'Patna, IN',
  'Pimpri, IN',
  'Pune, IN',
  'Raigarh Fort, IN',
  'Raipur, IN',
  'Rājkot, IN',
  'Rāmgundam, IN',
  'Ranchi, IN',
  'Sahāranpur, IN',
  'Salem, IN',
  'Sāngli, IN',
  'Shiliguri, IN',
  'Solāpur, IN',
  'Shyamnagar, IN',
  'Srinagar, IN',
  'Sūrat, IN',
  'Teni, IN',
  'Thāne, IN',
  'Tiruchirappalli, IN',
  'Tirunelveli, IN',
  'Thiruvananthapuram, IN',
  'Udaipur, IN',
  'Ujjain, IN',
  'Ulhasnagar, IN',
  'Vadodara, IN',
  'Vārānasi, IN',
  'Vijayawāda, IN',
  'Vishākhapatnam, IN',
  'Warangal, IN',
  'Jerusalem, IL',
  'Dublin, IE',
  'South Tangerang, ID',
  'City of Balikpapan, ID',
  'Masjid Jamie Baitul Muttaqien, ID',
  'Balikpapan, ID',
  'Bandung, ID',
  'Banjarmasin, ID',
  'Bekasi, ID',
  'Bogor, ID',
  'Cimahi, ID',
  'Denpasar, ID',
  'Depok, ID',
  'Jakarta, ID',
  'Jambi City, ID',
  'Malang, ID',
  'Manado, ID',
  'Padang, ID',
  'Palembang, ID',
  'Pekanbaru, ID',
  'Pontianak, ID',
  'Semarang, ID',
  'Situbondo, ID',
  'Surabaya, ID',
  'Surakarta, ID',
  'Tangerang, ID',
  'Bandarlampung, ID',
  'Makassar, ID',
  'Yogyakarta, ID',
  'Medan, ID',
  'Budapest, HU',
  'Carrefour, HT',
  'Port-au-Prince, HT',
  'Zagreb - Centar, HR',
  'Zagreb, HR',
  'San Pedro Sula, HN',
  'Tegucigalpa, HN',
  'Hong Kong, HK',
  'Kowloon, HK',
  'Guatemala City, GT',
  'Mixco, GT',
  'Villa Nueva, GT',
  'Athens, GR',
  'Camayenne, GN',
  'Conakry, GN',
  'Accra, GH',
  'Kumasi, GH',
  'Tbilisi, GE',
  'Birmingham, GB',
  'Bristol, GB',
  'Edinburgh, GB',
  'Glasgow, GB',
  'Leeds, GB',
  'Liverpool, GB',
  'London, GB',
  'City of London, GB',
  'Sheffield, GB',
  'Libreville, GA',
  'Lyon, FR',
  'Marseille, FR',
  'Paris, FR',
  'Toulouse, FR',
  'Helsinki, FI',
  'Addis Ababa, ET',
  'Barcelona, ES',
  'Madrid, ES',
  'Zaragoza, ES',
  'Málaga, ES',
  'Murcia, ES',
  'Palma, ES',
  'Sevilla, ES',
  'Valencia, ES',
  'Asmara, ER',
  'Alexandria, EG',
  'Al Jīzah, EG',
  'Al Maḩallah al Kubrá, EG',
  'Al Manşūrah, EG',
  'Cairo, EG',
  'Luxor, EG',
  'Suez, EG',
  'Asyūţ, EG',
  'Port Said, EG',
  'Tanda, EG',
  'Guayaquil, EC',
  'Quito, EC',
  'Algiers, DZ',
  'Constantine, DZ',
  'Oran, DZ',
  'Tébessa, DZ',
  'Boumerdas, DZ',
  'Santo Domingo Oeste, DO',
  'Santiago de los Caballeros, DO',
  'Santo Domingo, DO',
  'Copenhagen, DK',
  'Djibouti, DJ',
  'Berlin, DE',
  'Bremen, DE',
  'Dortmund, DE',
  'Dresden, DE',
  'Duisburg, DE',
  'Düsseldorf, DE',
  'Essen, DE',
  'Frankfurt am Main, DE',
  'Hamburg, DE',
  'Wandsbek, DE',
  'Hannover, DE',
  'Köln, DE',
  'Leipzig, DE',
  'München, DE',
  'Nürnberg, DE',
  'Stuttgart, DE',
  'Prague, CZ',
  'Havana, CU',
  'Santiago de Cuba, CU',
  'Barranquilla, CO',
  'Bogotá, CO',
  'Bucaramanga, CO',
  'Cali, CO',
  'Cartagena, CO',
  'Cúcuta, CO',
  'Ibagué, CO',
  'Medellín, CO',
  'Pereira, CO',
  'Santa Marta, CO',
  'Wenshan City, CN',
  'Ordos, CN',
  'Zhu Cheng City, CN',
  'Changshu City, CN',
  'Anshan, CN',
  'Baotou, CN',
  'Bei’an, CN',
  'Benxi, CN',
  'Changchun, CN',
  'Chaoyang, CN',
  'Chengde, CN',
  'Dandong, CN',
  'Datong, CN',
  'Fushun, CN',
  'Fuxin, CN',
  'Harbin, CN',
  'Hegang, CN',
  'Hohhot, CN',
  'Jiamusi, CN',
  'Jilin, CN',
  'Jinzhou, CN',
  'Jixi, CN',
  'Liaoyang, CN',
  'Liaoyuan, CN',
  'Mudanjiang, CN',
  'Panshan, CN',
  'Qiqihar, CN',
  'Shenyang, CN',
  'Shuangyashan, CN',
  'Siping, CN',
  'Yingkou, CN',
  'Zhangjiakou, CN',
  'Yueyang, CN',
  'Zhongshan, CN',
  'Suzhou, CN',
  'Shangyu, CN',
  'Baoding, CN',
  'Beijing, CN',
  'Bengbu, CN',
  'Cangzhou, CN',
  'Changsha, CN',
  'Changzhi, CN',
  'Changzhou, CN',
  'Chaozhou, CN',
  'Chengdu, CN',
  'Chongqing, CN',
  'Dalian, CN',
  'Dayan, CN',
  'Foshan, CN',
  'Fuzhou, CN',
  'Guangzhou, CN',
  'Guilin, CN',
  'Guiyang, CN',
  'Guli, CN',
  'Haikou, CN',
  'Jiaojiang, CN',
  'Handan, CN',
  'Hangzhou, CN',
  'Hefei, CN',
  'Hengshui, CN',
  'Hengyang, CN',
  'Huaibei, CN',
  'Huainan, CN',
  'Huangshi, CN',
  'Jiangmen, CN',
  'Jiaozuo, CN',
  'Jiaxing, CN',
  'Jinan, CN',
  'Jining, CN',
  'Kaifeng, CN',
  'Kunming, CN',
  'Langfang, CN',
  'Lanzhou, CN',
  'Wuwei, CN',
  'Guankou, CN',
  'Luancheng, CN',
  'Luohe, CN',
  'Luoyang, CN',
  'Luqiao, CN',
  'Nanchang, CN',
  'Nanchong, CN',
  'Nanjing, CN',
  'Nanning, CN',
  'Nantong, CN',
  'Neijiang, CN',
  'Ningbo, CN',
  'Dadukou, CN',
  'Pingdingshan, CN',
  'Puyang, CN',
  'Puyang, CN',
  'Qingdao, CN',
  "Huai'an, CN",
  'Qinhuangdao, CN',
  'Jieyang, CN',
  'Shanghai, CN',
  'Shantou, CN',
  'Shaoguan, CN',
  'Shaoxing, CN',
  'Shashi, CN',
  'Shenzhen, CN',
  'Shijiazhuang, CN',
  'Shiyan, CN',
  'Shiyan, CN',
  'Tai’an, CN',
  'Taiyuan, CN',
  'Taizhou, CN',
  'Tanggu, CN',
  'Tangshan, CN',
  'Tianjin, CN',
  'Tianshui, CN',
  'Wenzhou, CN',
  'Wuhan, CN',
  'Wuhu, CN',
  'Changde, CN',
  'Wuxi, CN',
  'Xiamen, CN',
  'Xi’an, CN',
  'Xiangyang, CN',
  'Xiangtan, CN',
  'Zhuhai, CN',
  'Xianyang, CN',
  'Xingtai, CN',
  'Xining, CN',
  'Xinxiang, CN',
  'Xinyang, CN',
  'Xuchang, CN',
  'Tongshan, CN',
  'Yancheng, CN',
  'Yangquan, CN',
  'Yangzhou, CN',
  'Yantai, CN',
  'Yichang, CN',
  'Yinchuan, CN',
  'Yunfu, CN',
  'Anyang, CN',
  'Zibo, CN',
  'Zhangzhou, CN',
  'Zhanjiang, CN',
  'Zhengzhou, CN',
  'Zhenjiang, CN',
  'Zhumadian, CN',
  'Zhuzhou, CN',
  'Zigong, CN',
  'Zunyi, CN',
  'Shihezi, CN',
  'Ürümqi, CN',
  'Douala, CM',
  'Garoua, CM',
  'Kousséri, CM',
  'Yaoundé, CM',
  'Puente Alto, CL',
  'Santiago, CL',
  'Abidjan, CI',
  'Abobo, CI',
  'Bouaké, CI',
  'Brazzaville, CG',
  'Pointe-Noire, CG',
  'Bangui, CF',
  'Masina, CD',
  'Kinshasa, CD',
  'Kolwezi, CD',
  'Likasi, CD',
  'Lubumbashi, CD',
  'Kananga, CD',
  'Kisangani, CD',
  'Mbuji-Mayi, CD',
  'Québec, CA',
  'Winnipeg, CA',
  'Vancouver, CA',
  'Toronto, CA',
  'Ottawa, CA',
  'North York, CA',
  'Montréal, CA',
  'Mississauga, CA',
  'Kitchener, CA',
  'Hamilton, CA',
  'Edmonton, CA',
  'Calgary, CA',
  'Brampton, CA',
  'Homyel’, BY',
  'Minsk, BY',
  'Jaboatão dos Guararapes, BR',
  'Aparecida de Goiânia, BR',
  'Manaus, BR',
  'Aracaju, BR',
  'Belford Roxo, BR',
  'Belo Horizonte, BR',
  'Brasília, BR',
  'Campinas, BR',
  'Campo Grande, BR',
  'Contagem, BR',
  'Cuiabá, BR',
  'Curitiba, BR',
  'Duque de Caxias, BR',
  'Feira de Santana, BR',
  'Florianópolis, BR',
  'Goiânia, BR',
  'Guarulhos, BR',
  'Joinville, BR',
  'Juiz de Fora, BR',
  'Londrina, BR',
  'Niterói, BR',
  'Nova Iguaçu, BR',
  'Osasco, BR',
  'Porto Alegre, BR',
  'Ribeirão das Neves, BR',
  'Ribeirão Preto, BR',
  'Rio de Janeiro, BR',
  'Salvador, BR',
  'Santo André, BR',
  'Santos, BR',
  'São Bernardo do Campo, BR',
  'São João de Meriti, BR',
  'São José dos Campos, BR',
  'São Paulo, BR',
  'Sorocaba, BR',
  'Uberlândia, BR',
  'Ananindeua, BR',
  'Belém, BR',
  'Fortaleza, BR',
  'Jaboatão, BR',
  'João Pessoa, BR',
  'Maceió, BR',
  'Natal, BR',
  'Recife, BR',
  'São Luís, BR',
  'Teresina, BR',
  'Cochabamba, BO',
  'La Paz, BO',
  'Santa Cruz de la Sierra, BO',
  'Cotonou, BJ',
  'Sofia, BG',
  'Ouagadougou, BF',
  'Antwerpen, BE',
  'Brussels, BE',
  'Khulna, BD',
  'Chittagong, BD',
  'Dhaka, BD',
  'Rājshāhi, BD',
  'Sarajevo, BA',
  'Baku, AZ',
  'Brisbane, AU',
  'Gold Coast, AU',
  'Melbourne, AU',
  'Sydney, AU',
  'Adelaide, AU',
  'Perth, AU',
  'Vienna, AT',
  'Córdoba, AR',
  'Mendoza, AR',
  'Rosario, AR',
  'Salta, AR',
  'San Juan, AR',
  'San Miguel de Tucumán, AR',
  'Santa Fe de la Vera Cruz, AR',
  'Buenos Aires, AR',
  'La Plata, AR',
  'Mar del Plata, AR',
  'Quilmes, AR',
  'Luanda, AO',
  'Yerevan, AM',
  'Kabul, AF',
  'Abu Dhabi, AE',
  'Al Ain, AE',
  'Sharjah, AE',
  'Dubai, AE',
]

export const getRandomCity = () => {
  return cities[random(0, cities.length - 1)]
}
